#Jasypt Config
jasypt:
  encryptor:
    bean: jasyptEncryptorBean
    # password: [VM Arguments OR Environment Variable] : Password for decrypting elements encrypted with jasypt

#JWT
jwt:
  secret-key: ENC(S7GPwu6uPVXhktuGgDomU2MxMUqHfw8w4jL5cQAtGYAD8CvjxOouxMkyPVAYWkjCxtc1NGRQQxKv8LSjYA2rtQ==)

#Database
spring:
  datasource:
    url: ENC(i/bTGZHhhAaw3KVhyyiVQ4PB0mg3aPLEJC35rJS0DT0uWVf4jFLV5F8qxVoxWZc+oUPEq6jLpPYeUkZzR9XDmQ==)
    driver-class-name: ENC(nkeB4qM7JXIrMFqgRniSr1ZqUzDXCa/TGIyuplg6+eX3Or261/ZL9Km6mReh7Qio)
    username: ENC(dXOnLsHMsIb618EB4m15ZAkpIzMosyTjO8KmPsdbg4M=)
    password: ENC(NmGGtfAWnOQfnYjKjdBgC9X5xlUnD41q3tFsmm3DnjU=)

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: ENC(lKvwvCfz+pBhgHMrDHoxMaTI09JBWvQ6kID2zNQS8o3eVs7QvwpzzSglXix/xRqa3GcGPNUiGPp5Z0OFUgZJmw==)
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(husM/ul0Gmac90Mxy/787G9QFcMmVNmacPd7Dn7RSwN2U5cB2T+sjAXp6urldST0)
    password: ENC(YIKPDEXi77tOMky9aeiT29Vir99kZYtE5T+JtRM6p6w=)
    properties:
      mail:
        smtp:
          auth:
            true
          starttls:
            enable: true

  #OAuth
  profiles:
    include: oauth

  #Swagger
  #/swagger-ui/index.html
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 80

resource:
  file:
    allow-extension: bmp,jpg,jpeg,png,gif
    url: /resources/files
    # path: [VM Arguments OR Environment Variable] : Actual storage path for uploaded files

email:
  receiver: ENC(/avjnkUU1LS4jWzORQIu9vzWPg4NAazDAMwnfZQBj2aA595bE9Zj5P97fhAKdixR)

bot:
  BOT_TOKEN: ENC(p5GwF9EU3aVU1Ms98Df5Lsfg3MUHjz1JrF/4lVHM0MFnD88W5w+FMljzJHfrWTKMODMy7sLwIdaqf3P+/Qjslg==)
  BOT_USERNAME: ENC(mLmTMljs06jJ0ymRNSz/jnwI50uFGarebOS/ER9dEiY=)
  CHAT_ID: ENC(/XIf4f+7H+YmBPVVFg7ntkplF0T7QDdQWRVKZYC0nc4=)